app: # 应用基本配置
  port: 443 # 应用端口
  app_name: go-gin # 应用名称
  app_url: https://www.mrjello.top # 应用域名
  env:  # 环境配置
    name: prod # 环境名称
    debug: false # 是否开启调试模式

log:
  level: info # 日志等级
  root_dir: ./storage/logs # 日志根目录
  filename: app.log # 日志文件名称
  format: json # 日志格式
  show_line: true # 是否显示调用行
  max_backups: 3 # 旧文件的最大个数
  max_size: 500 # 日志文件最大大小（MB）
  max_age: 28 # 旧文件的最大保留天数
  compress: true # 是否压缩