database = "postgres"

[app]
port = 18080
app_name = "Go-Gin"
app_url = "http://localhost"

[app.env]
name = "development"
debug = true

[log]
level = "debug"
root_dir = "./storage/logs"
filename = "app.log"
format = "json"
show_line = true
max_backups = 3
max_size = 500
max_age = 28
compress = true

[postgresql]
driver = "postgres"
host = "129.146.74.103"
port = 5432
dbname = "go_gin"
user = "root"
password = "zxs123123"
sslmode = "disable"
time_zone = "Asia/Shanghai"
charset = "utf8mb4"
max_idle_conns = 10
max_open_conns = 100
log_mode = "info"
enable_file_log_writer = true
log_filename = "postgresql.log"

[api]
prefix = "/api"
version = "v1"

[jwt]
secret = "3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s"
jwt_ttl = 43200
jwt_blacklist_grace_period = 10
refresh_grace_period = 1800

[redis]
host = "146.56.117.12"
port = 6379
db = 0
password = "zxs123123"
